language: node_js
node_js:
  - 7

services:
  - docker

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version 
  - docker build -t udagram-api-feed ./udagram-api-feed 
  - docker build -t udagram-api-user ./udagram-api-user 
  - docker build -t udagram-frontend ./udagram-frontend 
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-frontend jonaspdev/udagram-frontend:v1
  - docker tag udagram-api-user jonaspdev/udagram-api-user:v1
  - docker tag udagram-api-feed jonaspdev/udagram-api-feed:v1
  - docker tag reverseproxy jonaspdev/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose-build.yaml push